'''
Task 2
Load data
Download all comments from a subreddit of your choice using URL: https://api.pushshift.io/reddit/comment/search/
'''

import requests
import json

base_url = 'https://api.pushshift.io/reddit/comment/search/'


data = requests.get(base_url, {'subreddit': 'high'+'heels'})
f = open('31b.txt', 'a', encoding='utf-8')
# result = data.json()
for d in data:
    f.write(str(d))
f.close()
print(*data)


if __name__ == '__main__':
    pass

'''
---output---
b'{\n    "data": [\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "SemiTrai' b'nedApe",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_flai' b'r_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n            "author_flair_' b'text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_7umtvg1",\n            "author_pat' b'reon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "point those toes!",\n  ' b'          "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614731716,\n    ' b'        "gildings": {},\n            "id": "gph9s7l",\n            "is_submitter": false,\n            "link_id": "t3_lw9a0y",\n    ' b'        "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lw9a0y",\n            "permalink": "/r/HighH' b'eels/comments/lw9a0y/flexin_on_these_new_heels/gph9s7l/",\n            "retrieved_on": 1614735866,\n            "score": 1,\n      ' b'      "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5' b'_2rtlm",\n            "top_awarded_type": null,\n
          "total_awards_received": 0,\n            "treatment_tags": []\n        ' b'},\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "davtrez",\n           ' b' "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_flair_richtext": [],\n   ' b'         "author_flair_template_id": null,\n
           "author_flair_text": null,\n            "author_flair_text_color": null,\n ' b'           "author_flair_type": "text",\n            "author_fullname": "t2_5v1svmq7",\n            "author_patreon_flair": false,' b'\n            "author_premium": false,\n            "awarders": [],\n            "body": "You are absolutely gorgeous \\u2764\\ufe0f ' b'xx",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 161473162' b'4,\n            "gildings": {},\n            "id": "gph9luf",\n            "is_submitter": false,\n
    "link_id": "t3_lwagy3' b'",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lwagy3",\n            "permalink": "/' b'r/HighHeels/comments/lwagy3/pretty_pink_heels/gph9luf/",\n            "retrieved_on": 1614735783,\n            "score": 1,\n       ' b'     "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n
         "subreddit_id": "t5_' b'2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_tags": []\n        }' b',\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "Elvis_Imitator",\n     ' b'       "author_flair_background_color": null,\n            "author_flair_css_class": null,\n
        "author_flair_richtext": [' b'],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n            "author_flair_text_color": n' b'ull,\n            "author_flair_type": "text",\n            "author_fullname": "t2_3265mm92",\n            "author_patreon_flair": ' b'false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Those might be the sexiest things I' b'\\u2019ve ever seen.",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "create' b'd_utc": 1614730392,\n
         "gildings": {},\n            "id": "gph777q",\n            "is_submitter": false,\n            "lin' b'k_id": "t3_lvxoof",\n            "locked": false,\n            "no_follow": true,\n
      "parent_id": "t3_lvxoof",\n          ' b'  "permalink": "/r/HighHeels/comments/lvxoof/tony_biancos_and_fishnets_what_more_can_you_want/gph777q/",\n            "retrieved_' b'on": 1614734656,\n
         "score": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit' b'": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received' b'": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": nul' b'l,\n
 "author": "festivalfashionista",\n            "author_flair_background_color": null,\n            "author_flair_css' b'_class": null,\n            "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_' b'text": null,\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname"' b': "t2_h47iwh2",\n            "author_patreon_flair": false,\n            "author_premium": true,\n            "awarders": [],\n     ' b'       "body": "\\ud83d\\ude02",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n          ' b'  "created_utc": 1614728930,\n            "gildings": {},\n            "id": "gph4cas",\n            "is_submitter": true,\n        ' b'    "link_id": "t3_lwd5d7",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t1_gpgo7ap",\n ' b'           "permalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gph4cas/",\n            "retrieved_on": 1614733' b'312,\n            "score": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeel' b's",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n      ' b'      "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n         ' b'   "author": "festivalfashionista",\n            "author_flair_background_color": null,\n            "author_flair_css_class": nul' b'l,\n            "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,' b'\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_h47iwh' b'2",\n            "author_patreon_flair": false,\n            "author_premium": true,\n            "awarders": [],\n            "body' b'": "\\ud83d\\udc95",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_u' b'tc": 1614728913,\n            "gildings": {},\n
  "id": "gph4b3i",\n            "is_submitter": true,\n            "link_id' b'": "t3_lwd5d7",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t1_gpgoe9a",\n
         "' b'permalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gph4b3i/",\n            "retrieved_on": 1614733296,\n       ' b'     "score": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n        ' b'    "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n
       "treat' b'ment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author":' b' "festivalfashionista",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n         ' b'   "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text":
null,\n           ' b' "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_h47iwh2",\n        ' b'    "author_patreon_flair": false,\n
    "author_premium": true,\n            "awarders": [],\n            "body": "Likewise' b' \\ud83d\\ude0a",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n
          "created_utc"' b': 1614728904,\n            "gildings": {},\n            "id": "gph4ahe",\n            "is_submitter": true,\n            "link_id": ' b'"t3_lwd5d7",\n            "locked": false,\n            "no_follow": false,\n            "parent_id": "t1_gpgoovh",\n            "pe' b'rmalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gph4ahe/",\n            "retrieved_on": 1614733288,\n         ' b'   "score": 2,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n          ' b'  "subreddit_id": "t5_2rtlm",\n
         "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatme' b'nt_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "' b'van_chilla",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_' b'flair_richtext": [],\n
     "author_flair_template_id": null,\n            "author_flair_text": null,\n            "author_fl' b'air_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_3t4oj9h3",\n            "autho' b'r_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Snakeskin \\ud83e\\' b'udd29",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 161472' b'8614,\n            "gildings": {},\n            "id": "gph3qce",\n            "is_submitter": false,\n            "link_id": "t3_lw1' b'vc8",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lw1vc8",\n            "permalink":' b' "/r/HighHeels/comments/lw1vc8/any_love_for_dangling_oc/gph3qce/",\n            "retrieved_on": 1614733022,\n            "score": ' b'1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit' b'_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_tags": []' b'\n        },\n
      {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "van_chilla",' b'\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_flair_richte' b'xt": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n            "author_flair_text_col' b'or": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_3t4oj9h3",\n            "author_patreon_fl' b'air": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Sure any time \\ud83d\\ude18\\ud' b'83e\\udd70",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 16' b'14728537,\n            "gildings": {},\n            "id": "gph3kqy",\n            "is_submitter": false,\n            "link_id": "t3' b'_lwfpv1",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lwfpv1",\n            "permali' b'nk": "/r/HighHeels/comments/lwfpv1/hi_my_name_is_simone_can_i_be_your_new_assistant/gph3kqy/",\n            "retrieved_on": 16147' b'32948,\n            "score": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHe' b'els",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n    ' b'        "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n
  ' b'     "author": "vale0746",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n      ' b'      "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n        ' b'    "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_n8d4gwm",\n     ' b'       "author_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Mmmm' b'm a fine arse&amp;legs\\ud83d\\ude18",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n    ' b'        "created_utc": 1614727829,\n            "gildings": {},\n            "id": "gph277z",\n            "is_submitter": false,\n ' b'           "link_id": "t3_lvzxtt",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lvzx' b'tt",\n            "permalink": "/r/HighHeels/comments/lvzxtt/_/gph277z/",\n            "retrieved_on": 1614732296,\n            "sc' b'ore": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n
           "sub' b'reddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_tag' b's": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "jeselu' b'vz",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n
    "author_flair_ri' b'chtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n            "author_flair_text' b'_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_a54avj1h",\n            "author_patreo' b'n_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Great now flex your ass a' b'nd pussy on my face so I can make you cum and then I can admire your feet and heels",\n            "collapsed_because_crowd_contr' b'ol": null,\n            "comment_type": null,\n            "created_utc": 1614727610,\n            "gildings": {},\n            "id"' b': "gph1rtk",\n            "is_submitter": false,\n            "link_id": "t3_lw9a0y",\n            "locked": false,\n            "no' b'_follow": true,\n            "parent_id": "t3_lw9a0y",\n            "permalink": "/r/HighHeels/comments/lw9a0y/flexin_on_these_new' b'_heels/gph1rtk/",\n            "retrieved_on": 1614732091,\n            "score": 1,\n            "send_replies": true,\n            ' b'"stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n
          "top_awarded_type":' b' null,\n            "total_awards_received": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_awardings"' b': [],\n            "associated_award": null,\n            "author": "sissytasha_781",\n            "author_flair_background_color":' b' null,\n            "author_flair_css_class": null,\n            "author_flair_richtext": [],\n
          "author_flair_template_i' b'd": null,\n            "author_flair_text": null,\n            "author_flair_text_color": null,\n            "author_flair_type": "' b'text",\n            "author_fullname": "t2_afole6z2",\n            "author_patreon_flair": false,\n            "author_premium": fa' b'lse,\n            "awarders": [],\n            "body": "Not sure which is more impressive the
stretch or the heels?!",\n           ' b' "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614726243,\n            "' b'gildings": {},\n
   "id": "gpgz1l3",\n            "is_submitter": false,\n            "link_id": "t3_lw9a0y",\n            "' b'locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lw9a0y",\n
          "permalink": "/r/HighHeels/comm' b'ents/lw9a0y/flexin_on_these_new_heels/gpgz1l3/",\n            "retrieved_on": 1614730799,\n            "score": 1,\n            "se' b'nd_replies": true,\n
           "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n' b'            "top_awarded_type": null,\n            "total_awards_received": 0,\n
      "treatment_tags": []\n        },\n      ' b'  {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "redlump",\n            "author_' b'flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_flair_richtext": [],\n            ' b'"author_flair_template_id": "c98efe40-67bd-11e2-8e65-12313d14a568",\n
"author_flair_text": "send me heel pics ;)",\n   ' b'         "author_flair_text_color": "dark",\n            "author_flair_type": "text",\n            "author_fullname": "t2_wg0yitq"' b',\n
 "author_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body"' b': "So sexyy",\n            "collapsed_because_crowd_control": null,\n
  "comment_type": null,\n            "created_utc": ' b'1614726145,\n            "gildings": {},\n            "id": "gpgyuau",\n            "is_submitter": false,\n            "link_id": "' b't3_lw9a0y",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lw9a0y",\n            "perma' b'link": "/r/HighHeels/comments/lw9a0y/flexin_on_these_new_heels/gpgyuau/",\n            "retrieved_on": 1614730701,\n            "s' b'core": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "su' b'breddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_ta' b'gs": []\n        },\n        {\n            "all_awardings": [],\n
       "associated_award": null,\n            "author": "jump1' b'981",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_flair_r' b'ichtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n            "author_flair_tex' b't_color": null,\n            "author_flair_type": "text",\n
     "author_fullname": "t2_8cymhgqg",\n            "author_patre' b'on_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "I\'m guessing you are or
' b'were a dancer (ballet) at some point. Love this photo",\n            "collapsed_because_crowd_control": null,\n            "commen' b't_type": null,\n            "created_utc": 1614726067,\n
     "gildings": {},\n            "id": "gpgyolj",\n            "is_s' b'ubmitter": false,\n            "link_id": "t3_lw9a0y",\n            "locked": false,\n            "no_follow": true,\n
  "p' b'arent_id": "t3_lw9a0y",\n            "permalink": "/r/HighHeels/comments/lw9a0y/flexin_on_these_new_heels/gpgyolj/",\n            ' b'"retrieved_on": 1614730625,\n            "score": 1,\n
       "send_replies": true,\n            "stickied": false,\n           ' b' "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awar' b'ds_received": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_' b'award": null,\n            "author": "SexxyDom",\n
         "author_flair_background_color": null,\n            "author_flair_css' b'_class": null,\n            "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_' b'text": null,\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname"' b': "t2_9put54b3",\n            "author_patreon_flair": false,\n            "author_premium": true,\n            "awarders": [],\n    ' b'        "body": "I would love that so much! If you ever want to message me privately, you can send me your Kik.",\n            "c' b'ollapsed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614725881,\n            "gil' b'dings": {},\n            "id": "gpgyaur",\n
       "is_submitter": true,\n            "link_id": "t3_kx6ktd",\n            "lock' b'ed": false,\n            "no_follow": true,\n            "parent_id": "t1_gpfnj9q",\n            "permalink": "/r/HighHeels/comment' b's/kx6ktd/foot_dangle_for_my_naughty_boys_oc/gpgyaur/",\n            "retrieved_on": 1614730443,\n            "score": 1,\n         ' b'   "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2r' b'tlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_tags": []\n        },\n' b'        {\n            "all_awardings": [],\n            "associated_award": null,\n            "author": "festivalfashionista",\n  ' b'          "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "author_flair_richtext"' b': [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n
 "author_flair_text_color"' b': null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_h47iwh2",\n            "author_patreon_flair"' b': false,\n            "author_premium": true,\n            "awarders": [],\n            "body": "\\ud83d\\ude3d",\n            "collap' b'sed_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614724441,\n            "gildings' b'": {},\n            "id": "gpgvaps",\n            "is_submitter": true,\n            "link_id": "t3_lwd5d7",\n            "locked": ' b'false,\n            "no_follow": true,\n            "parent_id": "t1_gpgstbb",\n            "permalink": "/r/HighHeels/comments/lwd' b'5d7/love_these_clear_nude_pumps/gpgvaps/",\n            "retrieved_on": 1614728943,\n
  "score": 1,\n            "send_rep' b'lies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n      ' b'      "top_awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_tags": []\n        },\n        {\n  ' b'          "all_awardings": [],\n            "associated_award": null,\n            "author": "TheVoyuer",\n            "author_flai' b'r_background_color": null,\n            "author_flair_css_class": null,\n            "author_flair_richtext": [],\n            "aut' b'hor_flair_template_id": null,\n            "author_flair_text": null,\n            "author_flair_text_color": null,\n            "a' b'uthor_flair_type": "text",\n            "author_fullname": "t2_4f4z9xjd",\n
 "author_patreon_flair": false,\n            ' b'"author_premium": false,\n            "awarders": [],\n            "body": "As someone with an appreciation for women in heels, an' b"d the effect they
exude on the female form, this pair of d'Orsay pumps are devastatingly sexy on you... would love to see you po" b'sed standing in them, ideally in a leg barring skirt or dress. Thank you for sharing your photos!",\n            "collapsed_becau' b'se_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614724431,\n            "gildings": {},\n  ' b'          "id": "gpgva10",\n            "is_submitter": false,\n            "link_id": "t3_lw9a0y",\n            "locked": false,\n ' b'           "no_follow": true,\n            "parent_id": "t3_lw9a0y",\n            "permalink": "/r/HighHeels/comments/lw9a0y/flexi' b'n_on_these_new_heels/gpgva10/",\n            "retrieved_on": 1614728933,\n            "score": 3,\n            "send_replies": true' b',\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_' b'awarded_type": null,\n            "total_awards_received": 0,\n            "treatment_tags": []\n        },\n        {\n            "' b'all_awardings": [],\n            "associated_award": null,\n            "author": "thesunmachinegun",\n            "author_flair_ba' b'ckground_color": null,\n            "author_flair_css_class": null,\n            "author_flair_richtext": [],\n            "author_' b'flair_template_id": null,\n            "author_flair_text": null,\n
   "author_flair_text_color": null,\n            "autho' b'r_flair_type": "text",\n            "author_fullname": "t2_9yfgxfbf",\n            "author_patreon_flair": false,\n            "aut' b'hor_premium": false,\n            "awarders": [],\n            "body": "\\u2660\\ufe0f\\ud83d\\udd25\\ud83d\\udd25\\u2660\\ufe0f\\ud83c\\udf' b'c6\\u2660\\ufe0f\\ud83d\\udd25\\ud83d\\udd25\\u2660\\ufe0f",\n
          "collapsed_because_crowd_control": null,\n            "comment_t' b'ype": null,\n            "created_utc": 1614723768,\n            "gildings": {},\n            "id": "gpgtvw3",\n
 "is_subm' b'itter": false,\n            "link_id": "t3_lw9a0y",\n            "locked": false,\n            "no_follow": true,\n            "pare' b'nt_id": "t3_lw9a0y",\n            "permalink": "/r/HighHeels/comments/lw9a0y/flexin_on_these_new_heels/gpgtvw3/",\n            "re' b'trieved_on": 1614728258,\n            "score": 1,\n            "send_replies": true,\n            "stickied": false,\n
           "s' b'ubreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_' b'received": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_awa' b'rd": null,\n            "author": "Varna266xp",\n            "author_flair_background_color": null,\n
"author_flair_css_' b'class": null,\n            "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_t' b'ext": null,\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname":' b' "t2_77jrth2k",\n            "author_patreon_flair": false,\n            "author_premium": false,\n
 "awarders": [],\n    ' b'        "body": "Beautiful legs and the heels are the icing on the cake.",\n            "collapsed_because_crowd_control": null,\n' b'            "comment_type": null,\n
      "created_utc": 1614723264,\n            "gildings": {},\n            "id": "gpgstbb"' b',\n            "is_submitter": false,\n            "link_id": "t3_lwd5d7",\n            "locked": false,\n
           "no_follow": t' b'rue,\n            "parent_id": "t3_lwd5d7",\n            "permalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gp' b'gstbb/",\n            "retrieved_on":
1614727732,\n            "score": 1,\n            "send_replies": true,\n            "stickied' b'": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n
"top_awarded_type": null,\n  ' b'          "total_awards_received": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n   ' b'         "associated_award": null,\n            "author": "WhiteTexasBull",\n            "author_flair_background_color": null,\n  ' b'          "author_flair_css_class": null,\n            "author_flair_richtext": [],\n
"author_flair_template_id": null,' b'\n            "author_flair_text": null,\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n  ' b'          "author_fullname": "t2_3fjb7w66",\n            "author_patreon_flair": false,\n            "author_premium": false,\n    ' b'        "awarders": [],\n            "body": "You are absolutely stunning! And love the Cosmopolitan in Vegas , one of my favorit' b'e places in town :)",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "create' b'd_utc": 1614721416,\n
      "gildings": {},\n            "id": "gpgoovh",\n            "is_submitter": false,\n            "lin' b'k_id": "t3_lwd5d7",\n            "locked": false,\n            "no_follow": true,\n
   "parent_id": "t3_lwd5d7",\n          ' b'  "permalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gpgoovh/",\n            "retrieved_on": 1614725726,\n    ' b'        "score": 1,\n
          "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels",\n     ' b'       "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n            "tr' b'eatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "autho' b'r": "jonothonwick",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n            "' b'author_flair_richtext": [],\n            "author_flair_template_id": null,\n
     "author_flair_text": null,\n            "au' b'thor_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_1nd1tgmb",\n           ' b' "author_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Would love' b' my lips around each toe\\nSlowly, one by one",\n            "collapsed_because_crowd_control": null,\n            "comment_type": ' b'null,\n            "created_utc": 1614721377,\n            "gildings": {},\n            "id": "gpgolmf",\n            "is_submitter"' b': false,\n            "link_id": "t3_lvqqt4",\n            "locked": false,\n            "no_follow": true,\n            "parent_id"' b': "t3_lvqqt4",\n            "permalink": "/r/HighHeels/comments/lvqqt4/in_love_with_these/gpgolmf/",\n            "retrieved_on": ' b'1614725680,\n            "score": 2,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "H' b'ighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,' b'\n            "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n  ' b'          "author": "drputypfifeanddrum",\n            "author_flair_background_color": null,\n            "author_flair_css_class' b'": null,\n            "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text":' b' null,\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_' b'849if2du",\n            "author_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n         ' b'   "body": "Beautiful",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n            "crea' b'ted_utc": 1614721287,\n            "gildings": {},\n
 "id": "gpgoe9a",\n            "is_submitter": false,\n            "l' b'ink_id": "t3_lwd5d7",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_lwd5d7",\n
    ' b'    "permalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gpgoe9a/",\n            "retrieved_on": 1614725579,\n  ' b'          "score": 1,\n            "send_replies": true,\n
           "stickied": false,\n            "subreddit": "HighHeels",\n   ' b'         "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n
      "' b'treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n            "aut' b'hor": "explorer952878",\n            "author_flair_background_color": null,\n            "author_flair_css_class": null,\n         ' b'   "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n           ' b' "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_50fatdyt",\n       ' b'     "author_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n            "body": "Mmmm I' b' like to something else nude here \\ud83d\\ude09",\n            "collapsed_because_crowd_control": null,\n
  "comment_type"' b': null,\n            "created_utc": 1614721203,\n            "gildings": {},\n            "id": "gpgo7ap",\n            "is_submitte' b'r": false,\n            "link_id": "t3_lwd5d7",\n            "locked": false,\n            "no_follow": true,\n            "parent_i' b'd": "t3_lwd5d7",\n            "permalink": "/r/HighHeels/comments/lwd5d7/love_these_clear_nude_pumps/gpgo7ap/",\n            "retr' b'ieved_on": 1614725481,\n            "score": 1,\n            "send_replies": true,\n            "stickied": false,\n            "sub' b'reddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_re' b'ceived": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n
         "associated_award' b'": null,\n            "author": "link661",\n            "author_flair_background_color": null,\n            "author_flair_css_class' b'": null,\n            "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text":' b' null,\n            "author_flair_text_color": null,\n            "author_flair_type": "text",\n
      "author_fullname": "t2_' b'5t9bxa44",\n            "author_patreon_flair": false,\n            "author_premium": false,\n            "awarders": [],\n         ' b'   "body": "love your hose and heels!",\n            "collapsed_because_crowd_control": null,\n            "comment_type": null,\n ' b'           "created_utc": 1614721126,\n            "gildings": {},\n            "id": "gpgo0v3",\n            "is_submitter": false' b',\n            "link_id": "t3_lwagy3",\n            "locked": false,\n            "no_follow": true,\n            "parent_id": "t3_l' b'wagy3",\n            "permalink": "/r/HighHeels/comments/lwagy3/pretty_pink_heels/gpgo0v3/",\n            "retrieved_on": 16147253' b'93,\n            "score": 1,\n            "send_replies": true,\n            "stickied": false,\n            "subreddit": "HighHeels' b'",\n            "subreddit_id": "t5_2rtlm",\n            "top_awarded_type": null,\n            "total_awards_received": 0,\n       ' b'     "treatment_tags": []\n        },\n        {\n            "all_awardings": [],\n            "associated_award": null,\n          ' b'  "author": "andymacd1777",\n            "author_flair_background_color": null,\n
     "author_flair_css_class": null,\n     ' b'       "author_flair_richtext": [],\n            "author_flair_template_id": null,\n            "author_flair_text": null,\n       ' b'     "author_flair_text_color": null,\n            "author_flair_type": "text",\n            "author_fullname": "t2_7aesk8ma",\n   ' b'         "author_patreon_flair": false,\n            "author_premium": false,\n
      "awarders": [],\n            "body": "Lo' b've the stockings and the pink animal stilettos very you and neon certainly suit you yellow and pink x",\n            "collapsed_b' b'ecause_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614720642,\n            "gildings": {}' b',\n            "id": "gpgmx1g",\n            "is_submitter": false,\n            "link_id": "t3_lwagy3",\n            "locked": fals' b'e,\n            "no_follow": true,\n            "parent_id": "t3_lwagy3",\n            "permalink": "/r/HighHeels/comments/lwagy3/p' b'retty_pink_heels/gpgmx1g/",\n            "retrieved_on": 1614724845,\n            "score": 1,\n            "send_replies": true,\n  ' b'          "stickied": false,\n            "subreddit": "HighHeels",\n
  "subreddit_id": "t5_2rtlm",\n            "top_awar' b'ded_type": null,\n            "total_awards_received": 0,\n            "treatment_tags": []\n        },\n        {\n            "all_' b'awardings": [],\n            "associated_award": null,\n            "author": "MikDoe",\n            "author_flair_background_color' b'": null,\n            "author_flair_css_class": null,\n            "author_flair_richtext": [],\n            "author_flair_template' b'_id": null,\n            "author_flair_text": null,\n            "author_flair_text_color": null,\n            "author_flair_type":' b' "text",\n            "author_fullname": "t2_5awhwn5l",\n            "author_patreon_flair": false,\n            "author_premium": ' b'false,\n            "awarders": [],\n            "body": "you sexy princess!\\ud83d\\ude0d\\u2764\\ud83d\\udca6",\n            "collapse' b'd_because_crowd_control": null,\n            "comment_type": null,\n            "created_utc": 1614719720,\n            "gildings":' b' {},\n            "id": "gpgkrie",\n            "is_submitter": false,\n            "link_id": "t3_lwagy3",\n            "locked": f' b'alse,\n            "no_follow": true,\n            "parent_id": "t3_lwagy3",\n            "permalink": "/r/HighHeels/comments/lwagy' b'3/pretty_pink_heels/gpgkrie/",\n            "retrieved_on": 1614723770,\n            "score": 1,\n            "send_replies": true,' b'\n            "stickied": false,\n            "subreddit": "HighHeels",\n            "subreddit_id": "t5_2rtlm",\n            "top_a' b'warded_type": null,\n            "total_awards_received":
0,\n            "treatment_tags": []\n        }\n    ]\n}'
'''
